{"uuid": "1261a550-6743-41aa-b492-3edc5856c1b2", "children": ["9e017ec9-9f82-4369-b39c-0252cd191234"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000\n  (Session info: chrome=120.0.6099.217)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7129E4D02+56194]\n\t(No symbol) [0x00007FF7129504B2]\n\t(No symbol) [0x00007FF7127F76AA]\n\t(No symbol) [0x00007FF7127E0839]\n\t(No symbol) [0x00007FF7127E06EB]\n\t(No symbol) [0x00007FF7127DEE3D]\n\t(No symbol) [0x00007FF7127DF7CE]\n\t(No symbol) [0x00007FF7127ED6CD]\n\t(No symbol) [0x00007FF712804471]\n\t(No symbol) [0x00007FF71280937A]\n\t(No symbol) [0x00007FF7127DFEC6]\n\t(No symbol) [0x00007FF7128041CF]\n\t(No symbol) [0x00007FF7128826B4]\n\t(No symbol) [0x00007FF712865C23]\n\t(No symbol) [0x00007FF712834A45]\n\t(No symbol) [0x00007FF712835AD4]\n\tGetHandleVerifier [0x00007FF712D5D5BB+3695675]\n\tGetHandleVerifier [0x00007FF712DB6197+4059159]\n\tGetHandleVerifier [0x00007FF712DADF63+4025827]\n\tGetHandleVerifier [0x00007FF712A7F029+687785]\n\t(No symbol) [0x00007FF71295B508]\n\t(No symbol) [0x00007FF712957564]\n\t(No symbol) [0x00007FF7129576E9]\n\t(No symbol) [0x00007FF712948094]\n\tBaseThreadInitThunk [0x00007FF9C6487344+20]\n\tRtlUserThreadStart [0x00007FF9C6D026B1+33]\n\n", "trace": "  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\Shriram\\12 Batch\\Python_Revision 2023-24\\Framework_Credkart\\pytest_Credkart.zip\\Pytest_Credkart\\testCases\\conftest.py\", line 54, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in maximize_window\n    self.execute(command, params)\n  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\MY PC\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1705337794362, "stop": 1705338168371}], "start": 1705337794362, "stop": 1705338170989}